#!/bin/sh

if [ ! -e target/bbsync-0.1.0-SNAPSHOT.jar ]; then
    mvn clean install
fi

SEARCH_TEXT=$@

java -jar target/bbsync-0.1.0-SNAPSHOT.jar `grep "$SEARCH_TEXT" -l ~/Documents/bbsync/STAGE/*.txt | sed 's/\(.*\)\.txt/\1/g' | sort | uniq | xargs`
