#!/bin/sh

CMD_SEJDA=~/Downloads/sejda-console-1.0.0.M9/bin/sejda-console

SEARCH_TEXT=$@


if [ "$SEARCH_TEXT" == "" ]; then
    echo "Missing search text as argument, unable to create view."
    exit 1
fi

mkdir -p /tmp/bbsync

VIEW_FILENAME=`echo "/tmp/bbsync/$SEARCH_TEXT.pdf" | tr ' ' '_'`

rm -f $VIEW_FILENAME

PDF_FILELIST=`echo $SEARCH_TEXT | echo "egrep -e \"$(sed 's/ /" -e "/g')\" -l ~/Documents/bbsync/STAGE/*.txt" | sh | sed 's/\.txt//g' | sort | uniq | xargs`

$CMD_SEJDA merge -f $PDF_FILELIST -o $VIEW_FILENAME

gnome-open $VIEW_FILENAME
